<a href="https://colab.research.google.com/github/woodskd24/ChocolateHackathon/blob/main/ChocolateCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [72]:
import pandas as pd
import pandas_profiling as pp
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels as sm

In [73]:
cocoa = pd.read_csv("/content/drive/MyDrive/data.csv")

In [74]:
cocoa

,id,company_location,country_of_bean_origin,cocoa_percent,rating,sweet,nutty,cocoa,roasty,earthy,...,rich,dried.fruit,ingredient_Beans,ingredient_Sugar,ingredient_Sweetener,ingredient_Cocoa_Butter,ingredient_vanilla,ingredient_lecithin,ingredient_salt,number_of_ingredients
0,1,U.S.A.,Tanzania,76.0,3.25,No,No,Yes,No,No,...,Yes,No,Yes,Yes,Yes,Yes,No,No,No,3.0
1,2,U.S.A.,Dominican Republic,76.0,3.50,No,No,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
2,3,U.S.A.,Madagascar,76.0,3.75,No,No,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
3,4,U.S.A.,Other,68.0,3.00,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
4,5,U.S.A.,Other,80.0,3.25,No,No,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,2126,Other,Dominican Republic,70.0,3.75,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,Yes,4.0
2126,2127,Other,Blend,80.0,2.75,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,Yes,4.0
2127,2128,Other,Blend,75.0,3.00,No,No,Yes,No,Yes,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
2128,2129,Other,Other,70.0,3.25,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
2129,2130,Other,Belize,72.0,3.50,No,No,No,Yes,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0

In [75]:
while("" in cocoa) :
    cocoa.remove("")

print(cocoa)

        id company_location country_of_bean_origin  cocoa_percent  rating  \
0        1           U.S.A.               Tanzania           76.0    3.25
1        2           U.S.A.     Dominican Republic           76.0    3.50
2        3           U.S.A.             Madagascar           76.0    3.75
3        4           U.S.A.                  Other           68.0    3.00
4        5           U.S.A.                  Other           80.0    3.25
...    ...              ...                    ...            ...     ...
2125  2126            Other     Dominican Republic           70.0    3.75
2126  2127            Other                  Blend           80.0    2.75
2127  2128            Other                  Blend           75.0    3.00
2128  2129            Other                  Other           70.0    3.25
2129  2130            Other                 Belize           72.0    3.50

     sweet nutty cocoa roasty earthy  ... rich dried.fruit ingredient_Beans  \
0       No    No   Yes     No     No  ...  Yes          No              Yes
1       No    No   Yes     No     No  ...   No          No              Yes
2       No    No   Yes     No     No  ...   No          No              Yes
3       No    No    No     No     No  ...   No          No              Yes
4       No    No   Yes     No     No  ...   No          No              Yes
...    ...   ...   ...    ...    ...  ...  ...         ...              ...
2125    No    No    No     No     No  ...   No          No              Yes
2126    No    No    No     No     No  ...   No          No              Yes
2127    No    No   Yes     No    Yes  ...   No          No              Yes
2128    No    No    No     No     No  ...   No          No              Yes
2129    No    No    No    Yes     No  ...   No          No              Yes

     ingredient_Sugar ingredient_Sweetener ingredient_Cocoa_Butter  \
0                 Yes                  Yes                     Yes
1                 Yes                  Yes                     Yes
2                 Yes                  Yes                     Yes
3                 Yes                  Yes                     Yes
4                 Yes                  Yes                     Yes
...               ...                  ...                     ...
2125              Yes                  Yes                     Yes
2126              Yes                  Yes                     Yes
2127              Yes                  Yes                     Yes
2128              Yes                  Yes                     Yes
2129              Yes                  Yes                     Yes

     ingredient_vanilla ingredient_lecithin ingredient_salt  \
0                    No                  No              No
1                    No                  No              No
2                    No                  No              No
3                    No                  No              No
4                    No                  No              No
...                 ...                 ...             ...
2125                 No                  No             Yes
2126                 No                  No             Yes
2127                 No                  No              No
2128                 No                  No              No
2129                 No                  No              No

     number_of_ingredients
0                      3.0
1                      3.0
2                      3.0
3                      3.0
4                      3.0
...                    ...
2125                   4.0
2126                   4.0
2127                   3.0
2128                   3.0
2129                   3.0

[2130 rows x 33 columns]

In [76]:
cocoa.dropna()

,id,company_location,country_of_bean_origin,cocoa_percent,rating,sweet,nutty,cocoa,roasty,earthy,...,rich,dried.fruit,ingredient_Beans,ingredient_Sugar,ingredient_Sweetener,ingredient_Cocoa_Butter,ingredient_vanilla,ingredient_lecithin,ingredient_salt,number_of_ingredients
0,1,U.S.A.,Tanzania,76.0,3.25,No,No,Yes,No,No,...,Yes,No,Yes,Yes,Yes,Yes,No,No,No,3.0
1,2,U.S.A.,Dominican Republic,76.0,3.50,No,No,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
2,3,U.S.A.,Madagascar,76.0,3.75,No,No,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
3,4,U.S.A.,Other,68.0,3.00,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
4,5,U.S.A.,Other,80.0,3.25,No,No,Yes,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,2126,Other,Dominican Republic,70.0,3.75,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,Yes,4.0
2126,2127,Other,Blend,80.0,2.75,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,Yes,4.0
2127,2128,Other,Blend,75.0,3.00,No,No,Yes,No,Yes,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
2128,2129,Other,Other,70.0,3.25,No,No,No,No,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0
2129,2130,Other,Belize,72.0,3.50,No,No,No,Yes,No,...,No,No,Yes,Yes,Yes,Yes,No,No,No,3.0

In [77]:
for col in cocoa.columns:
    cocoa.loc[cocoa[col] == "Yes", col] = 1
    cocoa.loc[cocoa[col] == "No", col] = 0
    cocoa.loc[cocoa[col] == "Australia", col] = 0
    cocoa.loc[cocoa[col] == "Belgium", col] = 1
    cocoa.loc[cocoa[col] == "Canada", col] = 2
    cocoa.loc[cocoa[col] == "Ecuador", col] = 3
    cocoa.loc[cocoa[col] == "France", col] = 4
    cocoa.loc[cocoa[col] == "Italy", col] = 5
    cocoa.loc[cocoa[col] == "Other", col] = 6
    cocoa.loc[cocoa[col] == "U.S.A.", col] = 7
    cocoa.loc[cocoa[col] == "U.K.", col] = 8
    cocoa.loc[cocoa[col] == "Belize", col] = 9
    cocoa.loc[cocoa[col] == "Blend", col] = 10
    cocoa.loc[cocoa[col] == "Bolivia", col] = 11
    cocoa.loc[cocoa[col] == "Brazil", col] = 12
    cocoa.loc[cocoa[col] == "Colombia", col] = 13
    cocoa.loc[cocoa[col] == "Dominican Republic", col] = 14
    cocoa.loc[cocoa[col] == "Guatemala", col] = 15
    cocoa.loc[cocoa[col] == "Madagascar", col] = 16
    cocoa.loc[cocoa[col] == "Mexico", col] = 17
    cocoa.loc[cocoa[col] == "Nicaragua", col] = 18
    cocoa.loc[cocoa[col] == "Peru", col] = 19
    cocoa.loc[cocoa[col] == "Tanzania", col] = 20
    cocoa.loc[cocoa[col] == "Venezuela", col] = 21
    cocoa.loc[cocoa[col] == "Peru", col] = 22
    cocoa.loc[cocoa[col] == "Vietnam", col] = 23

In [78]:
cocoa

,id,company_location,country_of_bean_origin,cocoa_percent,rating,sweet,nutty,cocoa,roasty,earthy,...,rich,dried.fruit,ingredient_Beans,ingredient_Sugar,ingredient_Sweetener,ingredient_Cocoa_Butter,ingredient_vanilla,ingredient_lecithin,ingredient_salt,number_of_ingredients
0,1,7,20,76.0,3.25,0,0,1,0,0,...,1,0,1,1,1,1,0,0,0,3.0
1,2,7,14,76.0,3.50,0,0,1,0,0,...,0,0,1,1,1,1,0,0,0,3.0
2,3,7,16,76.0,3.75,0,0,1,0,0,...,0,0,1,1,1,1,0,0,0,3.0
3,4,7,6,68.0,3.00,0,0,0,0,0,...,0,0,1,1,1,1,0,0,0,3.0
4,5,7,6,80.0,3.25,0,0,1,0,0,...,0,0,1,1,1,1,0,0,0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,2126,6,14,70.0,3.75,0,0,0,0,0,...,0,0,1,1,1,1,0,0,1,4.0
2126,2127,6,10,80.0,2.75,0,0,0,0,0,...,0,0,1,1,1,1,0,0,1,4.0
2127,2128,6,10,75.0,3.00,0,0,1,0,1,...,0,0,1,1,1,1,0,0,0,3.0
2128,2129,6,6,70.0,3.25,0,0,0,0,0,...,0,0,1,1,1,1,0,0,0,3.0
2129,2130,6,9,72.0,3.50,0,0,0,1,0,...,0,0,1,1,1,1,0,0,0,3.0

In [79]:
cocoa.shape

(2130, 33)

In [80]:
cocoa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2130 entries, 0 to 2129
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2130 non-null   int64
 1   company_location         2130 non-null   object
 2   country_of_bean_origin   2130 non-null   object
 3   cocoa_percent            2130 non-null   float64
 4   rating                   2130 non-null   float64
 5   sweet                    2130 non-null   object
 6   nutty                    2130 non-null   object
 7   cocoa                    2130 non-null   object
 8   roasty                   2130 non-null   object
 9   earthy                   2130 non-null   object
 10  creamy                   2130 non-null   object
 11  sandy                    2130 non-null   object
 12  fatty                    2130 non-null   object
 13  floral                   2130 non-null   object
 14  intense                  2130 non-null   object
 15  spicy                    2130 non-null   object
 16  sour                     2130 non-null   object
 17  vanilla                  2130 non-null   object
 18  fruit                    2130 non-null   object
 19  molasses                 2130 non-null   object
 20  woody                    2130 non-null   object
 21  sticky                   2130 non-null   object
 22  coffee                   2130 non-null   object
 23  rich                     2130 non-null   object
 24  dried.fruit              2130 non-null   object
 25  ingredient_Beans         2130 non-null   object
 26  ingredient_Sugar         2130 non-null   object
 27  ingredient_Sweetener     2130 non-null   object
 28  ingredient_Cocoa_Butter  2130 non-null   object
 29  ingredient_vanilla       2130 non-null   object
 30  ingredient_lecithin      2130 non-null   object
 31  ingredient_salt          2130 non-null   object
 32  number_of_ingredients    2060 non-null   float64
dtypes: float64(3), int64(1), object(29)
memory usage: 549.3+ KB

In [81]:
Choc = cocoa.drop(columns = "id")

In [82]:
Choc[['company_location', 'country_of_bean_origin', 'sweet', 'nutty', 'cocoa', 'roasty', 'earthy', 'creamy', 'sandy', 'fatty', 'floral', 'intense', 'spicy', 'sour', 'vanilla', 'fruit', 'molasses', 'woody', 'sticky', 'coffee', 'rich', 'dried.fruit', 'ingredient_Beans', 'ingredient_Sugar', 'ingredient_Sweetener', 'ingredient_Cocoa_Butter', 'ingredient_vanilla ', 'ingredient_lecithin', 'ingredient_salt']] = Choc[['company_location', 'country_of_bean_origin', 'sweet', 'nutty', 'cocoa', 'roasty', 'earthy', 'creamy', 'sandy', 'fatty', 'floral', 'intense', 'spicy', 'sour', 'vanilla', 'fruit', 'molasses', 'woody', 'sticky', 'coffee', 'rich', 'dried.fruit', 'ingredient_Beans', 'ingredient_Sugar', 'ingredient_Sweetener', 'ingredient_Cocoa_Butter', 'ingredient_vanilla', 'ingredient_lecithin', 'ingredient_salt']].astype(int)

In [83]:
Choc[['ingredient_vanilla']] = Choc[['ingredient_vanilla']].apply(pd.to_numeric, errors='coerce')
Choc[['ingredient_vanilla']] = Choc[['ingredient_vanilla']].fillna(0).astype(np.int64)

In [84]:
print(Choc.dtypes)

company_location             int64
country_of_bean_origin       int64
cocoa_percent              float64
rating                     float64
sweet                        int64
nutty                        int64
cocoa                        int64
roasty                       int64
earthy                       int64
creamy                       int64
sandy                        int64
fatty                        int64
floral                       int64
intense                      int64
spicy                        int64
sour                         int64
vanilla                      int64
fruit                        int64
molasses                     int64
woody                        int64
sticky                       int64
coffee                       int64
rich                         int64
dried.fruit                  int64
ingredient_Beans             int64
ingredient_Sugar             int64
ingredient_Sweetener         int64
ingredient_Cocoa_Butter      int64
ingredient_vanilla           int64
ingredient_lecithin          int64
ingredient_salt              int64
number_of_ingredients      float64
ingredient_vanilla           int64
dtype: object

In [85]:
while("" in Choc) :
    Choc.remove("")

print(Choc)

      company_location  country_of_bean_origin  cocoa_percent  rating  sweet  \
0                    7                      20           76.0    3.25      0
1                    7                      14           76.0    3.50      0
2                    7                      16           76.0    3.75      0
3                    7                       6           68.0    3.00      0
4                    7                       6           80.0    3.25      0
...                ...                     ...            ...     ...    ...
2125                 6                      14           70.0    3.75      0
2126                 6                      10           80.0    2.75      0
2127                 6                      10           75.0    3.00      0
2128                 6                       6           70.0    3.25      0
2129                 6                       9           72.0    3.50      0

      nutty  cocoa  roasty  earthy  creamy  ...  dried.fruit  \
0         0      1       0       0       0  ...            0
1         0      1       0       0       0  ...            0
2         0      1       0       0       0  ...            0
3         0      0       0       0       0  ...            0
4         0      1       0       0       0  ...            0
...     ...    ...     ...     ...     ...  ...          ...
2125      0      0       0       0       0  ...            0
2126      0      0       0       0       0  ...            0
2127      0      1       0       1       0  ...            0
2128      0      0       0       0       0  ...            0
2129      0      0       1       0       0  ...            0

      ingredient_Beans  ingredient_Sugar  ingredient_Sweetener  \
0                    1                 1                     1
1                    1                 1                     1
2                    1                 1                     1
3                    1                 1                     1
4                    1                 1                     1
...                ...               ...                   ...
2125                 1                 1                     1
2126                 1                 1                     1
2127                 1                 1                     1
2128                 1                 1                     1
2129                 1                 1                     1

      ingredient_Cocoa_Butter  ingredient_vanilla  ingredient_lecithin  \
0                           1                   0                    0
1                           1                   0                    0
2                           1                   0                    0
3                           1                   0                    0
4                           1                   0                    0
...                       ...                 ...                  ...
2125                        1                   0                    0
2126                        1                   0                    0
2127                        1                   0                    0
2128                        1                   0                    0
2129                        1                   0                    0

      ingredient_salt  number_of_ingredients  ingredient_vanilla
0                   0                    3.0                    0
1                   0                    3.0                    0
2                   0                    3.0                    0
3                   0                    3.0                    0
4                   0                    3.0                    0
...               ...                    ...                  ...
2125                1                    4.0                    0
2126                1                    4.0                    0
2127                0                    3.0                    0
2128                0                    3.0                    0
2129                0                    3.0                    0

[2130 rows x 33 columns]

In [86]:
Choc.dropna()

,company_location,country_of_bean_origin,cocoa_percent,rating,sweet,nutty,cocoa,roasty,earthy,creamy,...,dried.fruit,ingredient_Beans,ingredient_Sugar,ingredient_Sweetener,ingredient_Cocoa_Butter,ingredient_vanilla,ingredient_lecithin,ingredient_salt,number_of_ingredients,ingredient_vanilla
0,7,20,76.0,3.25,0,0,1,0,0,0,...,0,1,1,1,1,0,0,0,3.0,0
1,7,14,76.0,3.50,0,0,1,0,0,0,...,0,1,1,1,1,0,0,0,3.0,0
2,7,16,76.0,3.75,0,0,1,0,0,0,...,0,1,1,1,1,0,0,0,3.0,0
3,7,6,68.0,3.00,0,0,0,0,0,0,...,0,1,1,1,1,0,0,0,3.0,0
4,7,6,80.0,3.25,0,0,1,0,0,0,...,0,1,1,1,1,0,0,0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,6,14,70.0,3.75,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,4.0,0
2126,6,10,80.0,2.75,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,4.0,0
2127,6,10,75.0,3.00,0,0,1,0,1,0,...,0,1,1,1,1,0,0,0,3.0,0
2128,6,6,70.0,3.25,0,0,0,0,0,0,...,0,1,1,1,1,0,0,0,3.0,0
2129,6,9,72.0,3.50,0,0,0,1,0,0,...,0,1,1,1,1,0,0,0,3.0,0

In [92]:
Choc['number_of_ingredients'].fillna((Choc['number_of_ingredients'].mean()), inplace=True)

In [93]:
Choc.isnull().sum()

company_location           0
country_of_bean_origin     0
cocoa_percent              0
rating                     0
sweet                      0
nutty                      0
cocoa                      0
roasty                     0
earthy                     0
creamy                     0
sandy                      0
fatty                      0
floral                     0
intense                    0
spicy                      0
sour                       0
vanilla                    0
fruit                      0
molasses                   0
woody                      0
sticky                     0
coffee                     0
rich                       0
dried.fruit                0
ingredient_Beans           0
ingredient_Sugar           0
ingredient_Sweetener       0
ingredient_Cocoa_Butter    0
ingredient_vanilla         0
ingredient_lecithin        0
ingredient_salt            0
number_of_ingredients      0
ingredient_vanilla         0
dtype: int64

In [94]:
Choc.shape

(2130, 33)

In [95]:
Choc.to_csv(r'/content/drive/MyDrive/ChocolateCleanOfficial1.csv', index = False)